#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifeq ($(CONFIG_SPL),y)
obj-y  := hioboard.o spl.o
else 
obj-y  := mx6sabresd.o
endif
